version: 2.1
orbs:
  python: circleci/python@2.1.1

workflows:
  test:
    jobs:
      - build_and_test

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.9.15
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install pytest
          command: pip install pytest==7.2.0
      - run:
          name: Run tests
          command: pytest

